// flow-typed signature: cdf9408ac177f7fb4718b6f24d7773e3
// flow-typed version: <<STUB>>/node-fetch_v^3.3.2/flow_v0.232.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-fetch/src/body' {
  declare module.exports: any;
}

declare module 'node-fetch/src/errors/abort-error' {
  declare module.exports: any;
}

declare module 'node-fetch/src/errors/base' {
  declare module.exports: any;
}

declare module 'node-fetch/src/errors/fetch-error' {
  declare module.exports: any;
}

declare module 'node-fetch/src/headers' {
  declare module.exports: any;
}

declare module 'node-fetch/src' {
  declare module.exports: any;
}

declare module 'node-fetch/src/request' {
  declare module.exports: any;
}

declare module 'node-fetch/src/response' {
  declare module.exports: any;
}

declare module 'node-fetch/src/utils/get-search' {
  declare module.exports: any;
}

declare module 'node-fetch/src/utils/is-redirect' {
  declare module.exports: any;
}

declare module 'node-fetch/src/utils/is' {
  declare module.exports: any;
}

declare module 'node-fetch/src/utils/multipart-parser' {
  declare module.exports: any;
}

declare module 'node-fetch/src/utils/referrer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-fetch/src/body.js' {
  declare module.exports: $Exports<'node-fetch/src/body'>;
}
declare module 'node-fetch/src/errors/abort-error.js' {
  declare module.exports: $Exports<'node-fetch/src/errors/abort-error'>;
}
declare module 'node-fetch/src/errors/base.js' {
  declare module.exports: $Exports<'node-fetch/src/errors/base'>;
}
declare module 'node-fetch/src/errors/fetch-error.js' {
  declare module.exports: $Exports<'node-fetch/src/errors/fetch-error'>;
}
declare module 'node-fetch/src/headers.js' {
  declare module.exports: $Exports<'node-fetch/src/headers'>;
}
declare module 'node-fetch/src/index' {
  declare module.exports: $Exports<'node-fetch/src'>;
}
declare module 'node-fetch/src/index.js' {
  declare module.exports: $Exports<'node-fetch/src'>;
}
declare module 'node-fetch/src/request.js' {
  declare module.exports: $Exports<'node-fetch/src/request'>;
}
declare module 'node-fetch/src/response.js' {
  declare module.exports: $Exports<'node-fetch/src/response'>;
}
declare module 'node-fetch/src/utils/get-search.js' {
  declare module.exports: $Exports<'node-fetch/src/utils/get-search'>;
}
declare module 'node-fetch/src/utils/is-redirect.js' {
  declare module.exports: $Exports<'node-fetch/src/utils/is-redirect'>;
}
declare module 'node-fetch/src/utils/is.js' {
  declare module.exports: $Exports<'node-fetch/src/utils/is'>;
}
declare module 'node-fetch/src/utils/multipart-parser.js' {
  declare module.exports: $Exports<'node-fetch/src/utils/multipart-parser'>;
}
declare module 'node-fetch/src/utils/referrer.js' {
  declare module.exports: $Exports<'node-fetch/src/utils/referrer'>;
}
