// flow-typed signature: 4d85030be75f75faf64f737b1d97b368
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.24.1/flow_v0.232.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
